# .github/workflows/deploy.yml
name: Deploy
on:
    push:
        branches:
            - main

concurrency:
  group: 'deploy'
  cancel-in-progress: true

jobs:
    build:
        uses: ./.github/workflows/build.yml
        permissions: {}

    deploy:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4

            - name: Download build artifact
              uses: actions/download-artifact@v4
              with:
                name: dist
                path: dist/

            - uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: dist
                  branch: gh-pages
                  clean-exclude: preview
                  force: false

            # - name: Setup Firebase Service Account
            #   run: |
            #     echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PEACEINTHEMIDDLEEAST }}' > $HOME/gcloud-key.json
            #     echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-key.json" >> $GITHUB_ENV

            # - name: Deploy to Firebase
            #   run: yarn exec firebase deploy --project peaceinthemiddleeast