name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - closed
jobs:
    deploy-preview:
        runs-on: ubuntu-latest
        steps:    
            - uses: actions/checkout@v4
            
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                node-version: 20.19.5
                cache: 'yarn'

            - name: Install dependencies
              if: github.event.action != 'closed'
              run: yarn install --frozen-lockfile

            - name: Build
              if: github.event.action != 'closed'
              run: yarn build
              
            - uses: rossjrw/pr-preview-action@v1
              with:
                  source-dir: dist
                  preview-branch: gh-pages
                  umbrella-dir: preview
                  action: auto
                  wait-for-pages-deployment: true
                  comment: true
                  qr-code: false