name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - closed
jobs:
    build:
        if: github.event.action != 'closed'
        uses: ./.github/workflows/build.yml
        permissions: {}
        with:
            base-url: /preview/pr-${{ github.event.pull_request.number }}/

    deploy-preview:
        needs: [build]
        if: always()
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:    
            - uses: actions/checkout@v4

            - name: Download build artifact
              if: github.event.action != 'closed'
              uses: actions/download-artifact@v4
              with:
                name: dist
                path: dist/
              
            - uses: rossjrw/pr-preview-action@v1
              with:
                  source-dir: dist
                  preview-branch: gh-pages
                  umbrella-dir: preview
                  action: auto
                  comment: true
                  qr-code: false